# Data Analysis and Visualization

In [1]:
from pathlib import Path
import sys

sys.path.append(str(Path("../").resolve()))

import pandas     as pd
import numpy      as np
import matplotlib as mp
from astropy.io   import fits

from config_loader import ConfigLoader
from data_loader import DataLoader

In [2]:
config = ConfigLoader(str(Path("../configs/config.yaml").resolve()))

data = DataLoader(config, verbosity = 1)

df_xROSITA = data.get_xROSITA()

df_xROSITA.head()

Filename: /Users/admin/Documents/GitHub/H20-xROSITA-Catalog-Matching/src/datasets/eRASS1_Main.v1.1.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU      16   (17863,)   uint8
  1  CATALOG       1 BinTableHDU    731   930203R x 252C   [23A, 32A, J, J, K, K, J, D, D, D, D, E, E, E, E, E, E, D, D, D, D, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, J, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, J, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, J, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, J, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, J, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, J, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, J, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, J, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, J, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, J, E, E, E, E, J, E, E, D, I, I, I, I, I, I, I, I, I]

,IAUNAME,DETUID,SKYTILE,ID_SRC,UID,UID_Hard,ID_CLUSTER,RA,DEC,RA_RAW,...,APE_POIS_S,FLAG_SP_SNR,FLAG_SP_BPS,FLAG_SP_SCL,FLAG_SP_LGA,FLAG_SP_GC_CONS,FLAG_NO_RADEC_ERR,FLAG_NO_EXT_ERR,FLAG_NO_CTS_ERR,FLAG_OPT
0,1eRASS J002937.2-310209,eb01_009120_020_ML00003_002_c010,9120,3,100912000003,200912000004,2,7.405249,-31.036103,7.405692,...,2.718602e-191,0,0,0,0,0,0,0,0,0
1,1eRASS J004207.0-283154,eb01_012120_020_ML00001_002_c010,12120,1,101212000001,201212000002,1,10.529384,-28.531842,10.529974,...,1.966783e-95,0,0,0,0,1,0,0,0,0
2,1eRASS J004922.3-293108,eb01_012120_020_ML00003_002_c010,12120,3,101212000003,201212000003,2,12.342955,-29.518980,12.342879,...,1.020700e-63,0,0,0,0,1,0,0,0,0
3,1eRASS J005448.9-311230,eb01_012120_020_ML00004_002_c010,12120,4,101212000004,201212000004,3,13.704105,-31.208436,13.704021,...,1.214732e-79,0,0,0,0,0,0,0,0,0
4,1eRASS J012910.8-214156,eb01_021111_020_ML00001_002_c010,21111,1,102111100001,202111100001,1,22.295165,-21.698998,22.294551,...,0.000000e+00,0,0,0,0,0,0,0,0,0